# Generated by Django 4.0.2 on 2022-02-13 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('13c1aabe-166b-4c8f-ae77-1a843c5525c0'), primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(db_index=True, max_length=3)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('17d02e2b-5219-4c3c-819c-62fa37ca1798'), primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.animal')),
            ],
        ),
    ]
