# Generated by Django 4.0.2 on 2022-02-15 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_animal_id_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b9365b3-e444-4313-9c3d-1ac0ba81be3e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b59a2515-ed8b-4514-8a6c-1b06d0f6eac7'), primary_key=True, serialize=False, unique=True),
        ),
    ]
