# Generated by Django 4.0.2 on 2022-02-15 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_animal_id_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b977911e-9a5f-4bd5-8178-5e0c54acfdd0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08dbb9bb-23ef-450a-af55-932d253cce55'), primary_key=True, serialize=False, unique=True),
        ),
    ]
