# Generated by Django 4.0.2 on 2022-02-15 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_animal_id_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3288c118-143f-4e34-8462-11ea8134ac23'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('441a1307-2483-4b51-b723-4ff2186329ca'), primary_key=True, serialize=False, unique=True),
        ),
    ]
