# Generated by Django 4.0.2 on 2022-02-15 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_animal_id_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('477e6163-6539-4ae4-8120-4f39f3230227'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17def20b-5553-4957-8c5f-5f6f7088fc5a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
